/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalFaqRouteImport } from './routes/legal.faq'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalDeleteAccountRouteImport } from './routes/legal.delete-account'
import { Route as LegalDataSafetyRouteImport } from './routes/legal.data-safety'
import { Route as LegalAdDisclosureRouteImport } from './routes/legal.ad-disclosure'
import { Route as AppWithdrawHistoryRouteImport } from './routes/app.withdraw-history'
import { Route as AppWithdrawRouteImport } from './routes/app.withdraw'
import { Route as AppTriviaRouteImport } from './routes/app.trivia'
import { Route as AppTapDashRouteImport } from './routes/app.tap-dash'
import { Route as AppSpinRouteImport } from './routes/app.spin'
import { Route as AppReferralsRouteImport } from './routes/app.referrals'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMissionsRouteImport } from './routes/app.missions'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppHowRewardsRouteImport } from './routes/app.how-rewards'
import { Route as AppGamesRouteImport } from './routes/app.games'
import { Route as AppAboutRouteImport } from './routes/app.about'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalFaqRoute = LegalFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDeleteAccountRoute = LegalDeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDataSafetyRoute = LegalDataSafetyRouteImport.update({
  id: '/data-safety',
  path: '/data-safety',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAdDisclosureRoute = LegalAdDisclosureRouteImport.update({
  id: '/ad-disclosure',
  path: '/ad-disclosure',
  getParentRoute: () => LegalRoute,
} as any)
const AppWithdrawHistoryRoute = AppWithdrawHistoryRouteImport.update({
  id: '/withdraw-history',
  path: '/withdraw-history',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppTriviaRoute = AppTriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => AppRoute,
} as any)
const AppTapDashRoute = AppTapDashRouteImport.update({
  id: '/tap-dash',
  path: '/tap-dash',
  getParentRoute: () => AppRoute,
} as any)
const AppSpinRoute = AppSpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHowRewardsRoute = AppHowRewardsRouteImport.update({
  id: '/how-rewards',
  path: '/how-rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/about': typeof AppAboutRoute
  '/app/games': typeof AppGamesRoute
  '/app/how-rewards': typeof AppHowRewardsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/spin': typeof AppSpinRoute
  '/app/tap-dash': typeof AppTapDashRoute
  '/app/trivia': typeof AppTriviaRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/withdraw-history': typeof AppWithdrawHistoryRoute
  '/legal/ad-disclosure': typeof LegalAdDisclosureRoute
  '/legal/data-safety': typeof LegalDataSafetyRoute
  '/legal/delete-account': typeof LegalDeleteAccountRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/faq': typeof LegalFaqRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/about': typeof AppAboutRoute
  '/app/games': typeof AppGamesRoute
  '/app/how-rewards': typeof AppHowRewardsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/spin': typeof AppSpinRoute
  '/app/tap-dash': typeof AppTapDashRoute
  '/app/trivia': typeof AppTriviaRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/withdraw-history': typeof AppWithdrawHistoryRoute
  '/legal/ad-disclosure': typeof LegalAdDisclosureRoute
  '/legal/data-safety': typeof LegalDataSafetyRoute
  '/legal/delete-account': typeof LegalDeleteAccountRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/faq': typeof LegalFaqRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app': typeof AppIndexRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/about': typeof AppAboutRoute
  '/app/games': typeof AppGamesRoute
  '/app/how-rewards': typeof AppHowRewardsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/spin': typeof AppSpinRoute
  '/app/tap-dash': typeof AppTapDashRoute
  '/app/trivia': typeof AppTriviaRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/withdraw-history': typeof AppWithdrawHistoryRoute
  '/legal/ad-disclosure': typeof LegalAdDisclosureRoute
  '/legal/data-safety': typeof LegalDataSafetyRoute
  '/legal/delete-account': typeof LegalDeleteAccountRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/faq': typeof LegalFaqRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/legal'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/about'
    | '/app/games'
    | '/app/how-rewards'
    | '/app/leaderboard'
    | '/app/missions'
    | '/app/profile'
    | '/app/referrals'
    | '/app/spin'
    | '/app/tap-dash'
    | '/app/trivia'
    | '/app/withdraw'
    | '/app/withdraw-history'
    | '/legal/ad-disclosure'
    | '/legal/data-safety'
    | '/legal/delete-account'
    | '/legal/disclaimer'
    | '/legal/faq'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/about'
    | '/app/games'
    | '/app/how-rewards'
    | '/app/leaderboard'
    | '/app/missions'
    | '/app/profile'
    | '/app/referrals'
    | '/app/spin'
    | '/app/tap-dash'
    | '/app/trivia'
    | '/app/withdraw'
    | '/app/withdraw-history'
    | '/legal/ad-disclosure'
    | '/legal/data-safety'
    | '/legal/delete-account'
    | '/legal/disclaimer'
    | '/legal/faq'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/legal'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/about'
    | '/app/games'
    | '/app/how-rewards'
    | '/app/leaderboard'
    | '/app/missions'
    | '/app/profile'
    | '/app/referrals'
    | '/app/spin'
    | '/app/tap-dash'
    | '/app/trivia'
    | '/app/withdraw'
    | '/app/withdraw-history'
    | '/legal/ad-disclosure'
    | '/legal/data-safety'
    | '/legal/delete-account'
    | '/legal/disclaimer'
    | '/legal/faq'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/faq': {
      id: '/legal/faq'
      path: '/faq'
      fullPath: '/legal/faq'
      preLoaderRoute: typeof LegalFaqRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/delete-account': {
      id: '/legal/delete-account'
      path: '/delete-account'
      fullPath: '/legal/delete-account'
      preLoaderRoute: typeof LegalDeleteAccountRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/data-safety': {
      id: '/legal/data-safety'
      path: '/data-safety'
      fullPath: '/legal/data-safety'
      preLoaderRoute: typeof LegalDataSafetyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/ad-disclosure': {
      id: '/legal/ad-disclosure'
      path: '/ad-disclosure'
      fullPath: '/legal/ad-disclosure'
      preLoaderRoute: typeof LegalAdDisclosureRouteImport
      parentRoute: typeof LegalRoute
    }
    '/app/withdraw-history': {
      id: '/app/withdraw-history'
      path: '/withdraw-history'
      fullPath: '/app/withdraw-history'
      preLoaderRoute: typeof AppWithdrawHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trivia': {
      id: '/app/trivia'
      path: '/trivia'
      fullPath: '/app/trivia'
      preLoaderRoute: typeof AppTriviaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tap-dash': {
      id: '/app/tap-dash'
      path: '/tap-dash'
      fullPath: '/app/tap-dash'
      preLoaderRoute: typeof AppTapDashRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spin': {
      id: '/app/spin'
      path: '/spin'
      fullPath: '/app/spin'
      preLoaderRoute: typeof AppSpinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referrals': {
      id: '/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missions': {
      id: '/app/missions'
      path: '/missions'
      fullPath: '/app/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/how-rewards': {
      id: '/app/how-rewards'
      path: '/how-rewards'
      fullPath: '/app/how-rewards'
      preLoaderRoute: typeof AppHowRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games': {
      id: '/app/games'
      path: '/games'
      fullPath: '/app/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppGamesRoute: typeof AppGamesRoute
  AppHowRewardsRoute: typeof AppHowRewardsRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppSpinRoute: typeof AppSpinRoute
  AppTapDashRoute: typeof AppTapDashRoute
  AppTriviaRoute: typeof AppTriviaRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppWithdrawHistoryRoute: typeof AppWithdrawHistoryRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppGamesRoute: AppGamesRoute,
  AppHowRewardsRoute: AppHowRewardsRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppSpinRoute: AppSpinRoute,
  AppTapDashRoute: AppTapDashRoute,
  AppTriviaRoute: AppTriviaRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppWithdrawHistoryRoute: AppWithdrawHistoryRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LegalRouteChildren {
  LegalAdDisclosureRoute: typeof LegalAdDisclosureRoute
  LegalDataSafetyRoute: typeof LegalDataSafetyRoute
  LegalDeleteAccountRoute: typeof LegalDeleteAccountRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalFaqRoute: typeof LegalFaqRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAdDisclosureRoute: LegalAdDisclosureRoute,
  LegalDataSafetyRoute: LegalDataSafetyRoute,
  LegalDeleteAccountRoute: LegalDeleteAccountRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalFaqRoute: LegalFaqRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
